apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: workspace-pipeline6-ref
spec:
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: clone-task
      taskRef:
        name: clone-task-ref
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
    - name: build-task
      taskRef:
        name: build-task-ref
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
      runAfter:
        - clone-task
    - name: sonar-task
      taskRef:
        name: sonar-task-ref
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
      runAfter:
        - build-task
    - name: send-message-to-teams
      taskRef:
        name: send-to-microsoft-teams
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
      runAfter:
        - sonar-task
    - name: kaniko-task
      taskRef:
        name: kaniko-task-ref
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
      runAfter:
        - send-message-to-teams
