apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-task-ref
spec:
  params:
    - name: github-url
      description: url of the repo.
      default: https://github.com/Gokul-C/DevOps-K8s-Security.git
    - name: directory
      description: name of the directory inside workspace
      default: kaniko-image-building3
  workspaces:
    - name: task-ws
      description: Workspace for sharing files between tasks
  steps:
    - name: clone-step
      image: bitnami/git
      workingDir: $(workspaces.task-ws.path)
      securityContext:
        runAsUser: 0
      command: ["/bin/sh"]
      args:
        - -c
        - |
            echo "Starting initial task"
            rm -rf kaniko-image-building3
            git clone https://github.com/Gokul-C/DevOps-K8s-Security.git $(workspaces.task-ws.path)/$(params.directory)
            sleep 15
            ls -la $(workspaces.task-ws.path)/$(params.directory)
            echo "Ending clone task"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task-ref
spec:
  params:
    - name: directory
      description: name of the directory inside workspace
      default: kaniko-image-building3
  workspaces:
    - name: task-ws
      description: Workspace for sharing files between tasks
  steps:
    - name: build-task
      image: maven
      workingDir: $(workspaces.task-ws.path)/$(params.directory)
      securityContext:
        runAsUser: 0
      command: ["/bin/sh"]
      args:
        - -c
        - |
            echo "Starting build task - Reading file from workspace"
            #cd $(workspaces.task-ws.path)/kaniko-image-building3
            mvn clean package
            echo "End final task"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sonar-task-ref
spec:
  params:
    - name: project-key
      description: Name (reference) of the project key in sonarqube.
      default: tekton-sonar
    - name: project-name
      description: Name (reference) of the project name in sonarqube.
      default: tekton-sonar
    - name: host-url
      description: Sonarqube hosted url.
      default: http://10.0.1.38:9000
    - name: sonar-token
      description: Sonarqube hosted url.
      default: sqp_f197446aaae8c2a83d5f09df398fef507afd7e01
    - name: directory
      description: name of the directory inside workspace
      default: kaniko-image-building3
  workspaces:
    - name: task-ws
      description: Workspace for sharing files between tasks
  steps:
    - name: sonar-task
      image: maven
      workingDir: $(workspaces.task-ws.path)/$(params.directory)
      securityContext:
        runAsUser: 0
      command: ["/bin/sh"]
      args:
        - -c
        - |
            echo "Starting sonar scanning task - Reading file from workspace"
            #cd $(workspaces.task-ws.path)/$(params.directory)
            mvn clean verify sonar:sonar -Dsonar.projectKey=$(params.project-key) -Dsonar.projectName='$(params.project-name)' -Dsonar.host.url=$(params.host-url) -Dsonar.token=$(params.sonar-token)
            echo "End sonar scanning"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: send-to-microsoft-teams
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Messaging
    tekton.dev/tags: messaging
    tekton.dev/displayName: "Send message to Microsoft Teams Channel"
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  description: >-
    These tasks post a simple message to a Microsoft Teams Channel.

    This task uses the Incoming Webhook functionality of Microsoft Teams

  params:
  - name: webhook-url-secret
    type: string
    description: Name of the secret with incoming webhook URL
    default: microsoft-teams-webhook-url-secret
  - name: webhook-url-secret-key
    type: string
    description: Key in the secret
    default: url
  - name: message
    type: string
    description: The message to notify about
    default: "Testing from tekton pipeline"
  steps:
  - name: post
    image: docker.io/curlimages/curl:7.70.0@sha256:031df77a11e5edded840bc761a845eab6e3c2edee22669fb8ad6d59484b6a1c4 #tag: 7.70.0
    script: |
      #!/usr/bin/env sh
      MESSAGE=$(echo "${MESSAGE}" | sed -e 's/\"/\\\\"/g')
      JSON="{\"text\": \"${MESSAGE}\" }"
      curl -X POST -H 'Content-Type: application/json' -d "${JSON}" "${WEBHOOK_URL}"
    env:
    - name: WEBHOOK_URL
      valueFrom:
        secretKeyRef:
          name: $(params.webhook-url-secret)
          key: $(params.webhook-url-secret-key)
    - name: MESSAGE
      value: $(params.message)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-task-ref
spec:
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
      default: gokulc780/tekton-image:v1
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      description: The build context used by Kaniko.
      default: '.'
    - name: EXTRA_ARGS
      type: array
      default: []
    - name: BUILDER_IMAGE
      description: The image on which builds will run (default is v1.5.1)
      default: gcr.io/kaniko-project/executor:debug
    - name: directory
      description: name of the directory inside workspace
      default: kaniko-image-building3
  workspaces:
    - name: task-ws
      description: Workspace for sharing files between tasks
    - name: dockerconfig
      description: Includes a docker `config.json`
      optional: true
      mountPath: /kaniko/.docker
  steps:
    - name: kaniko-task
      image: $(params.BUILDER_IMAGE)
      workingDir: $(workspaces.task-ws.path)/$(params.directory)
      #env:
      #  - name: DOCKER_CONFIG
      #    value: docker-creds
      securityContext:
        runAsUser: 0
      script: |
          cp -f "/workspace/task-ws/kaniko-image-building3/config.json" /kaniko/.docker/config.json
         /kaniko/executor $(params.EXTRA_ARGS) --dockerfile=$(params.DOCKERFILE) --context=$(params.CONTEXT) --destination=$(params.IMAGE) 
         
